name: Set Secrets

on: workflow_dispatch

jobs:
  set-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Set execute permissions
        run: chmod +x ./scripts/set-secrets.sh

      - name: Run set-secrets script
        run: ./scripts/set-secrets.sh
