name: Set Secrets

on:
  workflow_dispatch:
    inputs:
      ip_address:
        description: 'IP Address'
        required: true
      ssh_password:
        description: 'SSH Password'
        required: true
      ssl_email:
        description: 'SSL Email'
        required: true
      domain:
        description: 'Domain'
        required: true
      app_name:
        description: 'App Name'
        required: true

permissions:
  contents: read
  actions: write

jobs:
  set-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Set GitHub secrets
        run: |
          gh secret set IP_ADDRESS --body "${{ github.event.inputs.ip_address }}"
          gh secret set SSH_PASSWORD --body "${{ github.event.inputs.ssh_password }}"
          gh secret set SSL_EMAIL --body "${{ github.event.inputs.ssl_email }}"
          gh secret set DOMAIN --body "${{ github.event.inputs.domain }}"
          gh secret set APP_NAME --body "${{ github.event.inputs.app_name }}"
